name: Product management automations

on:
  issues:
    types:
      - opened

jobs:

  add-label:
    name: Add triage label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: triage

  add-to-project:
    name: Add project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.TOKEN }}
